name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Run Test
    steps:
      - name: Find the PR associated with this push on push trigger, if there is one.
        uses: jwalton/gh-find-current-pr@v1
        id: findPR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Setup python
        if: ( steps.findPR.outputs.pr == false && github.event_name == 'push' ) || github.event_name == 'pull_request'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        if: ( steps.findPR.outputs.pr == false && github.event_name == 'push' ) || github.event_name == 'pull_request'
        run: |
          sudo apt-get update
          sudo apt-get install -qq net-tools python3 udhcpd python-gst-1.0 python3-gi gir1.2-gtk-3.0
          sudo apt-get install -qq gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly
          sudo apt-get install -qq gcc libgirepository1.0-dev libgtk-3-dev pkg-config
          pip install -U pip
          pip install tox tox-gh-actions coveralls coverage[toml]
      - name: Test project with tox
        if: ( steps.findPR.outputs.pr == false && github.event_name == 'push' ) || github.event_name == 'pull_request'
        run: tox --sitepackages
      - name: Upload coverage to coveralls
        if: ( steps.findPR.outputs.pr == false && github.event_name == 'push' ) || github.event_name == 'pull_request'
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
